/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ContinentData, CountryLevel, StoreItem } from '../types';

export const CONTINENTS_DATA: ContinentData[] = [
  {
    id: 'south-america',
    name: 'América del Sur',
    tagline: 'Ritmo, pasión folclórica, tango tradicional y cumbres místicas',
    icon: '🌎',
    themeColor: '#10b981',
    accentColor: '#f59e0b',
    bgGrad: ['#031d14', '#1f1302'],
    countries: [
      {
        id: 'brazil-carnaval',
        countryName: 'Brasil',
        countryCode: 'BR',
        flagEmoji: '🇧🇷',
        levelName: 'Carnaval & Favelas de Río',
        culturalTheme: 'Samba Tradicional, Pandeiros & Cristo Redentor',
        continentId: 'south-america',
        difficulty: 'EASY',
        bpm: 128,
        baseSpeed: 420,
        themeColor: '#10b981', // Verde Brasil
        secondaryColor: '#eab308', // Amarillo Oro
        bgGradient: ['#042217', '#1c1b03'],
        description: 'Vibrante desfile con el Cristo Redentor en la cima y favelas multicolores al compás acústico de la samba brasileña y pandeiros.',
        synthStyle: 'samba',
        seed: 10423,
        landmark: 'favelas_rio',
        rewardCoins: 120,
      },
      {
        id: 'argentina-tango',
        countryName: 'Argentina',
        countryCode: 'AR',
        flagEmoji: '🇦🇷',
        levelName: 'Obelisco & Tango Porteño',
        culturalTheme: 'Tango Porteño, Bandoneón Acústico & Noche de Buenos Aires',
        continentId: 'south-america',
        difficulty: 'NORMAL',
        bpm: 130,
        baseSpeed: 440,
        themeColor: '#38bdf8', // Celeste Bandera
        secondaryColor: '#facc15', // Sol de Mayo
        bgGradient: ['#031828', '#1a1803'],
        description: 'Paseo nocturno por la Avenida 9 de Julio con el Obelisco porteño y melodías líricas de bandoneón y contrabajo.',
        synthStyle: 'tango',
        seed: 21980,
        landmark: 'obelisk_buenos_aires',
        rewardCoins: 160,
      },
      {
        id: 'peru-machu-picchu',
        countryName: 'Perú',
        countryCode: 'PE',
        flagEmoji: '🇵🇪',
        levelName: 'Machu Picchu Sagrado',
        culturalTheme: 'Música Andina, Zampoñas, Quenas & Cumbres Sagradas',
        continentId: 'south-america',
        difficulty: 'HARD',
        bpm: 142,
        baseSpeed: 470,
        themeColor: '#f97316', // Naranja Inca
        secondaryColor: '#ef4444', // Rojo
        bgGradient: ['#280e03', '#1e0505'],
        description: 'Ascenso a las terrazas del Huayna Picchu con el sonido puro de zampoñas andinas y quenas sobre abismos sagrados.',
        synthStyle: 'andina',
        seed: 33451,
        landmark: 'machu_picchu',
        rewardCoins: 220,
      },
      {
        id: 'colombia-esmeralda',
        countryName: 'Colombia',
        countryCode: 'CO',
        flagEmoji: '🇨🇴',
        levelName: 'Cumbia del Valle de Cocora',
        culturalTheme: 'Cumbia Tradicional, Gaitas & Acordeón Colombiano',
        continentId: 'south-america',
        difficulty: 'HARD',
        bpm: 146,
        baseSpeed: 480,
        themeColor: '#06b6d4', // Turquesa Esmeralda
        secondaryColor: '#ec4899', // Fucsia Orquídea
        bgGradient: ['#021d22', '#220419'],
        description: 'Flujo rítmico de acordeón folclórico y tamboras entre cascadas cristalinas y palmas de cera gigantes.',
        synthStyle: 'cumbia',
        seed: 49820,
        landmark: 'mountains',
        rewardCoins: 250,
      },
      {
        id: 'chile-andes-frost',
        countryName: 'Chile',
        countryCode: 'CL',
        flagEmoji: '🇨🇱',
        levelName: 'Cordillera de los Andes & Moáis',
        culturalTheme: 'Folclore de los Andes, Charangos & Estrellas de Atacama',
        continentId: 'south-america',
        difficulty: 'INSANE',
        bpm: 152,
        baseSpeed: 510,
        themeColor: '#0ea5e9', // Azul Glaciar
        secondaryColor: '#ef4444', // Rojo Estrella
        bgGradient: ['#021a2c', '#180303'],
        description: 'Travesía a través de cumbres andinas nevadas y antiguos monolitos Moái bajo cielos límpidos de Atacama.',
        synthStyle: 'andina',
        seed: 58210,
        landmark: 'moai',
        rewardCoins: 300,
      },
      {
        id: 'uruguay-candombe-glow',
        countryName: 'Uruguay',
        countryCode: 'UY',
        flagEmoji: '🇺🇾',
        levelName: 'Rambla & Candombe Tradicional',
        culturalTheme: 'Tambores de Candombe, Piano & Costa del Este',
        continentId: 'south-america',
        difficulty: 'NORMAL',
        bpm: 136,
        baseSpeed: 445,
        themeColor: '#38bdf8', // Celeste Río
        secondaryColor: '#facc15', // Sol Dorado
        bgGradient: ['#031726', '#1c1902'],
        description: 'Ritmo contagioso de repique, chico y piano acústico a lo largo de la rambla y costa marítima.',
        synthStyle: 'tango',
        seed: 61890,
        landmark: 'obelisk_buenos_aires',
        rewardCoins: 180,
      },
    ],
  },
  {
    id: 'north-america',
    name: 'América del Norte & Caribe',
    tagline: 'Tradiciones ancestrales, mariachi, paisajes majestuosos y auroras',
    icon: '🗽',
    themeColor: '#ec4899',
    accentColor: '#38bdf8',
    bgGrad: ['#25041a', '#031926'],
    countries: [
      {
        id: 'mexico-dia-muertos',
        countryName: 'México',
        countryCode: 'MX',
        flagEmoji: '🇲🇽',
        levelName: 'Chichén Itzá & Sones de Jalisco',
        culturalTheme: 'Mariachi Tradicional, Trompetas de Jalisco & Pirámides Mayas',
        continentId: 'north-america',
        difficulty: 'EASY',
        bpm: 132,
        baseSpeed: 425,
        themeColor: '#f43f5e', // Rosa Mexicano
        secondaryColor: '#eab308', // Cempasúchil
        bgGradient: ['#240212', '#241a02'],
        description: 'Imponente pirámide de Kukulcán con trompetas acústicas de mariachi y armonías de vihuela tradicional.',
        synthStyle: 'mariachi',
        seed: 61204,
        landmark: 'mayan_pyramid',
        rewardCoins: 130,
      },
      {
        id: 'usa-route-66',
        countryName: 'Estados Unidos',
        countryCode: 'US',
        flagEmoji: '🇺🇸',
        levelName: 'Nueva York & Ruta Clásica',
        culturalTheme: 'Big Band Jazz Acústico, Metales & Estatua de la Libertad',
        continentId: 'north-america',
        difficulty: 'NORMAL',
        bpm: 136,
        baseSpeed: 445,
        themeColor: '#3b82f6', // Azul Clásico
        secondaryColor: '#ef4444', // Rojo
        bgGradient: ['#05152e', '#1c0303'],
        description: 'Rascacielos majestuosos de Manhattan junto a la Estatua de la Libertad con metales y contrabajo acústico.',
        synthStyle: 'mariachi',
        seed: 71092,
        landmark: 'statue_liberty',
        rewardCoins: 170,
      },
      {
        id: 'canada-aurora',
        countryName: 'Canadá',
        countryCode: 'CA',
        flagEmoji: '🇨🇦',
        levelName: 'Auroras Boreales & Montañas',
        culturalTheme: 'Folk Orquestal de Montaña, Cuerdas & Glaciares',
        continentId: 'north-america',
        difficulty: 'HARD',
        bpm: 140,
        baseSpeed: 465,
        themeColor: '#10b981', // Verde Aurora
        secondaryColor: '#a855f7', // Violeta Cielo
        bgGradient: ['#021f15', '#160224'],
        description: 'Danza de luces polares sobre las Montañas Rocosas con armonías orquestales de cuerdas y maderas.',
        synthStyle: 'nordic_edm',
        seed: 82341,
        landmark: 'mountains',
        rewardCoins: 230,
      },
      {
        id: 'jamaica-reggae-dub',
        countryName: 'Jamaica',
        countryCode: 'JM',
        flagEmoji: '🇯🇲',
        levelName: 'Reggae Roots de Kingston',
        culturalTheme: 'Reggae Roots Acústico, Guitarra Skank & Palmeras',
        continentId: 'north-america',
        difficulty: 'HARD',
        bpm: 138,
        baseSpeed: 460,
        themeColor: '#eab308', // Amarillo Sol
        secondaryColor: '#10b981', // Verde Selva
        bgGradient: ['#221a02', '#021d13'],
        description: 'Compás cálido y orgánico de reggae tradicional caribeño entre palmeras doradas.',
        synthStyle: 'dub',
        seed: 90123,
        landmark: 'sound_system_reggae',
        rewardCoins: 260,
      },
      {
        id: 'cuba-havana-sunset',
        countryName: 'Cuba',
        countryCode: 'CU',
        flagEmoji: '🇨🇺',
        levelName: 'La Habana & Son Tradicional',
        culturalTheme: 'Son Cubano, Clave Acústica, Trompetas & Malecón',
        continentId: 'north-america',
        difficulty: 'INSANE',
        bpm: 148,
        baseSpeed: 495,
        themeColor: '#f97316', // Ámbar Callejero
        secondaryColor: '#06b6d4', // Azul Caribe
        bgGradient: ['#220d02', '#021e24'],
        description: 'Polirritmo tradicional de son cubano con piano montuno, bongós y brisa marina.',
        synthStyle: 'samba',
        seed: 94812,
        landmark: 'colosseum',
        rewardCoins: 310,
      },
    ],
  },
  {
    id: 'europe',
    name: 'Europa',
    tagline: 'Orquestas clásicas, guitarras flamencas, acordeones y palacios barrocos',
    icon: '🏰',
    themeColor: '#a855f7',
    accentColor: '#06b6d4',
    bgGrad: ['#1d052a', '#031728'],
    countries: [
      {
        id: 'spain-flamenco',
        countryName: 'España',
        countryCode: 'ES',
        flagEmoji: '🇪🇸',
        levelName: 'Sagrada Familia & Flamenco',
        culturalTheme: 'Guitarra Flamenca Acústica, Palmas & Torres de Gaudí',
        continentId: 'europe',
        difficulty: 'EASY',
        bpm: 134,
        baseSpeed: 430,
        themeColor: '#ef4444', // Rojo Pasión
        secondaryColor: '#eab308', // Oro
        bgGradient: ['#260404', '#211802'],
        description: 'Fascinantes agujas neogóticas de la Sagrada Familia con el compás de palmas andaluzas y guitarras españolas.',
        synthStyle: 'flamenco',
        seed: 11234,
        landmark: 'sagrada_familia',
        rewardCoins: 140,
      },
      {
        id: 'france-tour-eiffel',
        countryName: 'Francia',
        countryCode: 'FR',
        flagEmoji: '🇫🇷',
        levelName: 'Torre Eiffel & Vals Parisino',
        culturalTheme: 'Acordeón Musette Parisino, Cuerdas Clásicas & Torre Eiffel',
        continentId: 'europe',
        difficulty: 'NORMAL',
        bpm: 138,
        baseSpeed: 450,
        themeColor: '#38bdf8', // Azul Francia
        secondaryColor: '#f43f5e', // Rosa
        bgGradient: ['#041a2e', '#23030d'],
        description: 'La Ciudad de la Luz bajo la silueta de la Torre Eiffel con dulces melodías de acordeón francés.',
        synthStyle: 'french_touch',
        seed: 23451,
        landmark: 'eiffel',
        rewardCoins: 180,
      },
      {
        id: 'italy-venezia-matrix',
        countryName: 'Italia',
        countryCode: 'IT',
        flagEmoji: '🇮🇹',
        levelName: 'Coliseo & Serenata de Cuerdas',
        culturalTheme: 'Mandolinas Italianas, Serenata Romana & Orquesta de Cámara',
        continentId: 'europe',
        difficulty: 'HARD',
        bpm: 140,
        baseSpeed: 465,
        themeColor: '#10b981', // Verde Esmeralda
        secondaryColor: '#f97316', // Terracota
        bgGradient: ['#021e14', '#250f03'],
        description: 'El legendario Coliseo Romano iluminado con arpegios de mandolina y cuerdas renacentistas.',
        synthStyle: 'italodisco',
        seed: 35672,
        landmark: 'colosseum',
        rewardCoins: 240,
      },
      {
        id: 'germany-berlin-techno',
        countryName: 'Alemania',
        countryCode: 'DE',
        flagEmoji: '🇩🇪',
        levelName: 'Puerta de Brandeburgo Sinfónica',
        culturalTheme: 'Orquesta Filarmónica, Metales Heroicos & Puerta de Brandeburgo',
        continentId: 'europe',
        difficulty: 'INSANE',
        bpm: 148,
        baseSpeed: 490,
        themeColor: '#eab308', // Amarillo
        secondaryColor: '#a855f7', // Violeta
        bgGradient: ['#1c1702', '#220404'],
        description: 'La histórica Puerta de Brandeburgo al son de una marcha orquestal clásica y timbales solemnes.',
        synthStyle: 'techno',
        seed: 48901,
        landmark: 'brandenburg_gate',
        rewardCoins: 320,
      },
      {
        id: 'uk-london-underground',
        countryName: 'Reino Unido',
        countryCode: 'GB',
        flagEmoji: '🇬🇧',
        levelName: 'Big Ben & Fanfarria Real',
        culturalTheme: 'Marcha Celta & Orquesta Real Londinense',
        continentId: 'europe',
        difficulty: 'DEMON',
        bpm: 156,
        baseSpeed: 520,
        themeColor: '#8b5cf6', // Violeta
        secondaryColor: '#38bdf8', // Azul Real
        bgGradient: ['#170327', '#021828'],
        description: 'El emblemático Big Ben marcando la marcha orquestal en las orillas del río Támesis.',
        synthStyle: 'celtic',
        seed: 59123,
        landmark: 'big_ben',
        rewardCoins: 400,
      },
      {
        id: 'netherlands-amsterdam-hardstyle',
        countryName: 'Países Bajos',
        countryCode: 'NL',
        flagEmoji: '🇳🇱',
        levelName: 'Molinos de Viento & Armonía Holandesa',
        culturalTheme: 'Música Tradicional de Viento, Carillón & Canales de Ámsterdam',
        continentId: 'europe',
        difficulty: 'HARD',
        bpm: 144,
        baseSpeed: 475,
        themeColor: '#f97316', // Naranja Oranje
        secondaryColor: '#06b6d4', // Azul Canales
        bgGradient: ['#240d02', '#021a22'],
        description: 'Molinos históricos con aspas majestuosas entre campos de tulipanes y armonías tradicionales.',
        synthStyle: 'french_touch',
        seed: 63451,
        landmark: 'windmill',
        rewardCoins: 270,
      },
    ],
  },
  {
    id: 'asia',
    name: 'Asia',
    tagline: 'Flautas de bambú, arpas koto, raga de sitar y templos de dragones',
    icon: '⛩️',
    themeColor: '#ef4444',
    accentColor: '#facc15',
    bgGrad: ['#280404', '#211802'],
    countries: [
      {
        id: 'japan-tokyo-sakura',
        countryName: 'Japón',
        countryCode: 'JP',
        flagEmoji: '🇯🇵',
        levelName: 'Monte Fuji & Sakura Tradicional',
        culturalTheme: 'Flauta Shakuhachi, Arpa Koto & Torii Flotante',
        continentId: 'asia',
        difficulty: 'EASY',
        bpm: 132,
        baseSpeed: 435,
        themeColor: '#ec4899', // Rosa Sakura
        secondaryColor: '#06b6d4', // Cyan
        bgGradient: ['#240316', '#021924'],
        description: 'El Monte Fuji nevado y la Puerta Torii flotante rodeada de flores de cerezo con flauta shakuhachi y arpa koto.',
        synthStyle: 'sakura',
        seed: 67123,
        landmark: 'fuji_torii',
        rewardCoins: 150,
      },
      {
        id: 'korea-seoul-kpop',
        countryName: 'Corea del Sur',
        countryCode: 'KR',
        flagEmoji: '🇰🇷',
        levelName: 'N Seoul Tower & Armonía Tradicional',
        culturalTheme: 'Cítara Gayageum, Flauta Daegeum & Seúl Imperial',
        continentId: 'asia',
        difficulty: 'NORMAL',
        bpm: 138,
        baseSpeed: 455,
        themeColor: '#06b6d4', // Cyan Brillante
        secondaryColor: '#f43f5e', // Rosa
        bgGradient: ['#021b22', '#22030f'],
        description: 'La Torre N de Seúl elevándose sobre palacios tradicionales con cítaras coreanas de madera.',
        synthStyle: 'kpop',
        seed: 92341,
        landmark: 'seoul_tower',
        rewardCoins: 200,
      },
      {
        id: 'china-imperial-dragon',
        countryName: 'China',
        countryCode: 'CN',
        flagEmoji: '🇨🇳',
        levelName: 'Pagodas & Gran Muralla Imperial',
        culturalTheme: 'Guzheng Tradicional, Flauta Dizi & Gran Muralla',
        continentId: 'asia',
        difficulty: 'HARD',
        bpm: 144,
        baseSpeed: 480,
        themeColor: '#ef4444', // Rojo Dragón
        secondaryColor: '#eab308', // Oro Imperial
        bgGradient: ['#290303', '#251a02'],
        description: 'Paseo por las almenas de la Gran Muralla y pagodas imperiales con arpegios de guzheng y flauta dizi.',
        synthStyle: 'oriental',
        seed: 78912,
        landmark: 'pagoda',
        rewardCoins: 250,
      },
      {
        id: 'india-holi-synth',
        countryName: 'India',
        countryCode: 'IN',
        flagEmoji: '🇮🇳',
        levelName: 'Taj Mahal & Sitar Sagrado',
        culturalTheme: 'Raga Tradicional, Sitar, Flauta Bansuri & Taj Mahal',
        continentId: 'asia',
        difficulty: 'INSANE',
        bpm: 150,
        baseSpeed: 510,
        themeColor: '#f59e0b', // Azafrán
        secondaryColor: '#8b5cf6', // Violeta Místico
        bgGradient: ['#241502', '#140324'],
        description: 'El legendario Taj Mahal reflejado en estanques cristalinos con la resonancia sagrada del sitar y bansuri.',
        synthStyle: 'raga',
        seed: 89012,
        landmark: 'taj_mahal',
        rewardCoins: 330,
      },
      {
        id: 'thailand-bangkok-rush',
        countryName: 'Tailandia',
        countryCode: 'TH',
        flagEmoji: '🇹🇭',
        levelName: 'Wat Arun & Campanas del Templo',
        culturalTheme: 'Música Sagrada Tailandesa, Campanas & Farolillos',
        continentId: 'asia',
        difficulty: 'DEMON',
        bpm: 160,
        baseSpeed: 540,
        themeColor: '#eab308', // Oro Templo
        secondaryColor: '#10b981', // Verde Esmeralda
        bgGradient: ['#241b02', '#021c13'],
        description: 'El majestuoso templo de Wat Arun rodeado de farolillos flotantes y percusiones ceremoniales de campanas.',
        synthStyle: 'oriental',
        seed: 98765,
        landmark: 'pagoda',
        rewardCoins: 420,
      },
    ],
  },
  {
    id: 'africa',
    name: 'África',
    tagline: 'Marimbas ancestrales, tambores djembe, sabana estelar y cantos tradicionales',
    icon: '🦁',
    themeColor: '#f59e0b',
    accentColor: '#10b981',
    bgGrad: ['#241302', '#021a11'],
    countries: [
      {
        id: 'egypt-pyramid-hologram',
        countryName: 'Egipto',
        countryCode: 'EG',
        flagEmoji: '🇪🇬',
        levelName: 'Pirámides de Giza Ancestrales',
        culturalTheme: 'Música Clásica Egipcia, Laúd Oud, Flauta Ney & Nilo',
        continentId: 'africa',
        difficulty: 'EASY',
        bpm: 130,
        baseSpeed: 425,
        themeColor: '#facc15', // Oro Faraónico
        secondaryColor: '#06b6d4', // Azul Nilo
        bgGradient: ['#221902', '#021820'],
        description: 'Las Grandes Pirámides de Giza y la Esfinge bajo cielos despejados con escalas de laúd oud y flauta ney.',
        synthStyle: 'oriental',
        seed: 14567,
        landmark: 'pyramid',
        rewardCoins: 150,
      },
      {
        id: 'kenya-savannah-sunset',
        countryName: 'Kenia',
        countryCode: 'KE',
        flagEmoji: '🇰🇪',
        levelName: 'Sabana & Kilimanjaro',
        culturalTheme: 'Marimba Tradicional, Árboles de Acacia & Coros Africanos',
        continentId: 'africa',
        difficulty: 'NORMAL',
        bpm: 136,
        baseSpeed: 445,
        themeColor: '#ea580c', // Naranja Atardecer
        secondaryColor: '#facc15', // Amarillo Sabana
        bgGradient: ['#230d02', '#211802'],
        description: 'Carrera bajo árboles de acacia y el majestuoso Kilimanjaro con cálidas marimbas de madera y percusión tribal.',
        synthStyle: 'afrobeat',
        seed: 25678,
        landmark: 'safari_savanna',
        rewardCoins: 190,
      },
      {
        id: 'south-africa-cape-neon',
        countryName: 'Sudáfrica',
        countryCode: 'ZA',
        flagEmoji: '🇿🇦',
        levelName: 'Table Mountain & Tambores del Cabo',
        culturalTheme: 'Folclore Sudafricano, Piano Acústico & Ciudad del Cabo',
        continentId: 'africa',
        difficulty: 'HARD',
        bpm: 144,
        baseSpeed: 475,
        themeColor: '#10b981', // Verde Esmeralda
        secondaryColor: '#3b82f6', // Azul Océano
        bgGradient: ['#021c13', '#031427'],
        description: 'Cálidas melodías de piano y tambores acústicos a orillas de las costas sudafricanas.',
        synthStyle: 'afrobeat',
        seed: 36789,
        landmark: 'safari_savanna',
        rewardCoins: 250,
      },
      {
        id: 'morocco-medina-glow',
        countryName: 'Marruecos',
        countryCode: 'MA',
        flagEmoji: '🇲🇦',
        levelName: 'Medina de Marrakech',
        culturalTheme: 'Música Gnawa Tradicional, Guembri & Mosaicos Andalusíes',
        continentId: 'africa',
        difficulty: 'INSANE',
        bpm: 152,
        baseSpeed: 505,
        themeColor: '#f43f5e', // Rosa Marrakech
        secondaryColor: '#06b6d4', // Azul Cobalto
        bgGradient: ['#23030d', '#021822'],
        description: 'Laberinto de callejones y mezquitas históricas con melodías hipnóticas de laúd y guembri.',
        synthStyle: 'oriental',
        seed: 47890,
        landmark: 'castle',
        rewardCoins: 330,
      },
      {
        id: 'nigeria-lagos-afrobeats',
        countryName: 'Nigeria',
        countryCode: 'NG',
        flagEmoji: '🇳🇬',
        levelName: 'Lagos & Tambores Parlantes',
        culturalTheme: 'Percusión Tradicional Yoruba, Talking Drums & Viento',
        continentId: 'africa',
        difficulty: 'DEMON',
        bpm: 160,
        baseSpeed: 540,
        themeColor: '#22c55e', // Verde Lagos
        secondaryColor: '#eab308', // Oro
        bgGradient: ['#031c0c', '#201802'],
        description: 'La máxima prueba africana: percusión desenfrenada de tambores parlantes y vientos tradicionales.',
        synthStyle: 'afrobeat',
        seed: 58901,
        landmark: 'safari_savanna',
        rewardCoins: 420,
      },
    ],
  },
  {
    id: 'oceania',
    name: 'Oceanía',
    tagline: 'Arrecifes de coral, didgeridoo ancestral, ukeleles y espíritus del Pacífico',
    icon: '🏄',
    themeColor: '#06b6d4',
    accentColor: '#ec4899',
    bgGrad: ['#021c25', '#24041b'],
    countries: [
      {
        id: 'australia-sydney-harbor',
        countryName: 'Australia',
        countryCode: 'AU',
        flagEmoji: '🇦🇺',
        levelName: 'Ópera de Sídney & Outback',
        culturalTheme: 'Didgeridoo Aborigen, Ópera de Sídney & Tierra Roja',
        continentId: 'oceania',
        difficulty: 'EASY',
        bpm: 132,
        baseSpeed: 430,
        themeColor: '#06b6d4', // Azul Coral
        secondaryColor: '#f97316', // Ocre Australiano
        bgGradient: ['#021b24', '#241002'],
        description: 'Las velas arquitectónicas de la Ópera de Sídney reflejadas en la bahía con el resonar del didgeridoo.',
        synthStyle: 'pacific',
        seed: 69012,
        landmark: 'sydney_opera',
        rewardCoins: 150,
      },
      {
        id: 'new-zealand-fjord-glow',
        countryName: 'Nueva Zelanda',
        countryCode: 'NZ',
        flagEmoji: '🇳🇿',
        levelName: 'Fiordos & Canto Maori',
        culturalTheme: 'Canto Sagrado Maori, Flauta Putorino & Helechos Verdes',
        continentId: 'oceania',
        difficulty: 'NORMAL',
        bpm: 138,
        baseSpeed: 450,
        themeColor: '#10b981', // Verde Helecho
        secondaryColor: '#38bdf8', // Azul Glaciar
        bgGradient: ['#021c13', '#031726'],
        description: 'Fiordos majestuosos y cavernas de estalactitas con los cantos solemnes de la tradición maorí.',
        synthStyle: 'pacific',
        seed: 70123,
        landmark: 'mountains',
        rewardCoins: 190,
      },
      {
        id: 'fiji-coral-lagoon',
        countryName: 'Fiyi',
        countryCode: 'FJ',
        flagEmoji: '🇫🇯',
        levelName: 'Laguna de Coral & Ukeleles',
        culturalTheme: 'Guitarras del Pacífico, Ukelele Acústico & Olas Tropicales',
        continentId: 'oceania',
        difficulty: 'HARD',
        bpm: 144,
        baseSpeed: 475,
        themeColor: '#38bdf8', // Turquesa
        secondaryColor: '#ec4899', // Coral Rosa
        bgGradient: ['#031826', '#220417'],
        description: 'Arrecifes tropicales y aguas cristalinas al ritmo de guitarras acústicas y suaves ukeleles.',
        synthStyle: 'pacific',
        seed: 81234,
        landmark: 'tiki',
        rewardCoins: 250,
      },
      {
        id: 'hawaii-volcano-wave',
        countryName: 'Hawái',
        countryCode: 'US-HI',
        flagEmoji: '🌺',
        levelName: 'Volcán Kilauea & Guitarras Slack-Key',
        culturalTheme: 'Guitarra Hawaiana Slack-Key, Tambores Ipu & Olas Gigantes',
        continentId: 'oceania',
        difficulty: 'INSANE',
        bpm: 152,
        baseSpeed: 510,
        themeColor: '#f43f5e', // Magma Fucsia
        secondaryColor: '#f59e0b', // Fuego Dorado
        bgGradient: ['#25030e', '#231502'],
        description: 'Tierras volcánicas y olas oceánicas acompañadas por la tradicional guitarra slack-key y tambores ipu.',
        synthStyle: 'pacific',
        seed: 92345,
        landmark: 'mountains',
        rewardCoins: 340,
      },
      {
        id: 'polynesia-tiki-storm',
        countryName: 'Polinesia',
        countryCode: 'PF',
        flagEmoji: '🏝️',
        levelName: 'Moái Ancestral & Tambores Pahu',
        culturalTheme: 'Tótem Sagrado, Tambores Pahu de Madera & Océano Pacífico',
        continentId: 'oceania',
        difficulty: 'DEMON',
        bpm: 162,
        baseSpeed: 545,
        themeColor: '#a855f7', // Violeta Pacífico
        secondaryColor: '#06b6d4', // Cyan Relámpago
        bgGradient: ['#160324', '#021824'],
        description: 'El clímax oceánico: estatuas Moái colosales y el potente redoble de los tradicionales tambores pahu de madera.',
        synthStyle: 'pacific',
        seed: 99999,
        landmark: 'moai',
        rewardCoins: 450,
      },
    ],
  },
];

// Flat list of all 30 Country Levels
export const ALL_COUNTRY_LEVELS: CountryLevel[] = CONTINENTS_DATA.flatMap((c) => c.countries);

// STORE ITEMS CATALOG (Buy with in-game coins!)
export const STORE_ITEMS: StoreItem[] = [
  // --- SKINS (AVATARES) ---
  {
    id: 'classic',
    name: 'Cubo Clásico',
    category: 'skin',
    price: 0,
    description: 'El legendario cubo geométrico. Ágil, equilibrado y confiable.',
    icon: '✦',
    badge: 'INICIAL',
  },
  {
    id: 'cyborg',
    name: 'Visor Ciborg',
    category: 'skin',
    price: 150,
    description: 'Casco cibernético con sensor láser y escaneo perimetral.',
    icon: '■',
  },
  {
    id: 'tango_dancer',
    name: 'Bailarín de Tango',
    category: 'skin',
    price: 250,
    description: 'Sombrero gardeliano clásico y pañuelo carmesí de compadrito porteño.',
    icon: '🎩',
    badge: 'CULTURAL',
  },
  {
    id: 'ninja',
    name: 'Shinobi de las Sombras',
    category: 'skin',
    price: 300,
    description: 'Placa de combate sigilosa con visor ninja aerodinámico.',
    icon: '▲',
  },
  {
    id: 'viking',
    name: 'Guerrero Nórdico',
    category: 'skin',
    price: 380,
    description: 'Yelmo con cuernos ancestrales forjados en hierro vikingo.',
    icon: '⚔️',
    badge: 'NÓRDICO',
  },
  {
    id: 'astronaut',
    name: 'Cosmonauta Orbital',
    category: 'skin',
    price: 450,
    description: 'Traje de exploración espacial con visor de oro antirradiación.',
    icon: '👨‍🚀',
    badge: 'ESPACIAL',
  },
  {
    id: 'demon',
    name: 'Vórtice Infernal',
    category: 'skin',
    price: 500,
    description: 'Cuernos angulares afilados y ojos de fuego demoníaco.',
    icon: '◈',
    badge: 'POPULAR',
  },
  {
    id: 'samba_king',
    name: 'Rey del Carnaval',
    category: 'skin',
    price: 600,
    description: 'Exuberante corona de plumas doradas y esmeraldas del sambódromo.',
    icon: '🦚',
    badge: 'FESTIVAL',
  },
  {
    id: 'gladiator',
    name: 'Gladiador Romano',
    category: 'skin',
    price: 680,
    description: 'Casco de bronce imperial con cresta de crin de caballo roja.',
    icon: '🛡️',
    badge: 'IMPERIAL',
  },
  {
    id: 'dragon',
    name: 'Dragón Imperial',
    category: 'skin',
    price: 750,
    description: 'Armadura dorada inspirada en los guardianes de jade ancestrales.',
    icon: '🐲',
    badge: 'LEGENDARIO',
  },
  {
    id: 'alien',
    name: 'Visitante Alienígena',
    category: 'skin',
    price: 850,
    description: 'Visor bioluminiscente extraterrestre con antenas de plasma.',
    icon: '👽',
    badge: 'CÓSMICO',
  },
  {
    id: 'pixel_knight',
    name: 'Caballero 16-Bits',
    category: 'skin',
    price: 920,
    description: 'Armadura de acero pixelada estilo arcade retro con yelmo.',
    icon: '👾',
    badge: 'RETRO',
  },
  {
    id: 'pharaoh',
    name: 'Faraón Solar',
    category: 'skin',
    price: 1000,
    description: 'Tocado real de oro macizo y amatista con grabado de Horus.',
    icon: '👑',
    badge: 'MÍTICO',
  },
  {
    id: 'cyber_phoenix',
    name: 'Fénix Solar',
    category: 'skin',
    price: 1150,
    description: 'Alas radiantes de energía solar incandescente y cresta ígnea.',
    icon: '🦅',
    badge: 'FUEGO',
  },
  {
    id: 'skull',
    name: 'Calavera Calaverita',
    category: 'skin',
    price: 1250,
    description: 'Inspirada en el Día de Muertos con flores fluorescentes.',
    icon: '💀',
    badge: 'FESTIVAL',
  },
  {
    id: 'samurai',
    name: 'Shogun Cuántico',
    category: 'skin',
    price: 1600,
    description: 'Yoroi de nanotecnología con cuernos cromados.',
    icon: '⚡',
    badge: 'ÉLITE',
  },
  {
    id: 'cyborg_golden',
    name: 'Ciborg de Oro 24K',
    category: 'skin',
    price: 2000,
    description: 'Carrocería de oro pulido macizo con circuitos de diamantes puros.',
    icon: '💎',
    badge: 'SUPREMO',
  },

  // --- ESTELAS (TRAILS) ---
  {
    id: 'glow',
    name: 'Resplandor Neón',
    category: 'trail',
    price: 0,
    description: 'Estela suave de luz fluorescente continua.',
    icon: '⭕',
    badge: 'BÁSICO',
  },
  {
    id: 'rainbow',
    name: 'Arcoíris Cromático',
    category: 'trail',
    price: 250,
    description: 'Espectro completo RGB que oscila dinámicamente.',
    icon: '🌈',
    badge: 'COLOR',
  },
  {
    id: 'particles',
    name: 'Tormenta de Chispas',
    category: 'trail',
    price: 450,
    description: 'Emite lluvia de chispas electromagnéticas brillantes.',
    icon: '⚡',
  },
  {
    id: 'fire',
    name: 'Jet de Plasma',
    category: 'trail',
    price: 650,
    description: 'Llamarada continua de propulsión a reacción.',
    icon: '🔥',
    badge: 'FUEGO',
  },
  {
    id: 'matrix',
    name: 'Código Matrix',
    category: 'trail',
    price: 850,
    description: 'Rastro de glifos binarios digitales color verde esmeralda.',
    icon: '💾',
    badge: 'CYBER',
  },
  {
    id: 'sakura',
    name: 'Pétalos Sakura',
    category: 'trail',
    price: 1100,
    description: 'Pétalos de cerezo flotantes que caen suavemente al avanzar.',
    icon: '🌸',
    badge: 'ZEN',
  },

  // --- EFECTOS DE EXPLOSIÓN / DERROTA ---
  {
    id: 'shatter',
    name: 'Desintegración Neón',
    category: 'deathEffect',
    price: 0,
    description: 'El cubo se divide en fragmentos geométricos luminosos.',
    icon: '💥',
    badge: 'BÁSICO',
  },
  {
    id: 'implosion',
    name: 'Agujero Negro',
    category: 'deathEffect',
    price: 350,
    description: 'Colapso gravitatorio que absorbe luz antes de detonar.',
    icon: '🕳️',
  },
  {
    id: 'pixelate',
    name: 'Glitch 8-Bits',
    category: 'deathEffect',
    price: 600,
    description: 'Explosión de píxeles retro y distorsión CRT arcade.',
    icon: '👾',
    badge: 'RETRO',
  },
  {
    id: 'supernova',
    name: 'Supernova Estelar',
    category: 'deathEffect',
    price: 1200,
    description: 'Destello de onda expansiva estelar de alta potencia.',
    icon: '✨',
    badge: 'CÓSMICO',
  },
];
